# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('_', 'Медь'), ('А', 'Алюминий')], max_length=2)),
                ('insulation', models.CharField(choices=[('В', 'Поливинилхлорид'), ('Пв', 'Сшитый полиэтилен'), ('П', 'Полимерные композиции, не содержащие галогенов')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cable',
            name='specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koorsuch_app.Specs'),
        ),
    ]
