# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koorsuch_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specs',
            new_name='Spec',
        ),
        migrations.RenameField(
            model_name='cable',
            old_name='specs',
            new_name='spec',
        ),
    ]
