# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koorsuch_app', '0002_auto_20170420_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='extra_gauge',
            field=models.FloatField(choices=[(1.5, 1.5), (2.5, 2.5), (4, 4), (6, 6), (10, 10), (16, 16), (25, 25), (35, 35), (50, 50), (70, 70), (95, 95), (120, 120), (150, 150), (185, 185), (240, 240), (300, 300), (400, 400), (500, 500), (625, 625), (630, 630), (800, 800), (1000, 1000)], null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='extra_wires',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cable',
            name='gauge',
            field=models.FloatField(choices=[(1.5, 1.5), (2.5, 2.5), (4, 4), (6, 6), (10, 10), (16, 16), (25, 25), (35, 35), (50, 50), (70, 70), (95, 95), (120, 120), (150, 150), (185, 185), (240, 240), (300, 300), (400, 400), (500, 500), (625, 625), (630, 630), (800, 800), (1000, 1000)], default=0),
        ),
        migrations.AddField(
            model_name='cable',
            name='wire',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='spec',
            name='armor',
            field=models.CharField(choices=[('Г', 'Небронированный'), ('Б', 'Броня из стальных оцинкованных лент'), ('Ба', 'Броня из лент алюминия или его сплава'), ('К', 'Броня из круглых стальных оцинкованных проволок'), ('Ка', 'Броня из проволок алюминия или его сплава')], default='E', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='climate',
            field=models.CharField(choices=[('У', 'Умеренный климат'), ('ХЛ', 'Холодный климат'), ('УХЛ', 'Умеренный и холодный климат'), ('Т', 'Тропический климат'), ('М', 'Морской умеренно-холодный климат'), ('О', 'Общеклиматическое исполнение'), ('ОМ', 'Общеклиматическое морское исполнение'), ('В', 'Всеклиматическое исполнение')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='firefighting_cat',
            field=models.CharField(blank=True, choices=[('', 'Не распространяющие горение при одиночной прокладке'), ('нг(A F/R)', 'Не распространяющие горение при групповой прокладке по категории A F/R'), ('нг(A)', 'Не распространяющие горение при групповой прокладке по категории A'), ('нг(B)', 'Не распространяющие горение при групповой прокладке по категории B')], max_length=300),
        ),
        migrations.AddField(
            model_name='spec',
            name='firefighting_spec',
            field=models.CharField(choices=[('-LS', 'С пониженным дымо- и газовыделением'), ('-HF', 'Не выделяющие коррозионно-активных газообразных продуктов при горении'), ('-FRLS', 'Огнестойкие, с пониженным дымо- и газовыделением'), ('-FRHF', 'Огнестойкие и не выделяющие коррозионно-активных газообразных продуктов при горении')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='implementation',
            field=models.CharField(choices=[('ок', 'Однопроволочные круглые'), ('мк', 'Многопроволочные круглые'), ('ос', 'Однопроволочные секторные или сегментные'), ('мс', 'Многопроволочные секторные или сегментные')], default='E', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='protection',
            field=models.CharField(choices=[('В', 'Наружная оболочка из поливинилхлоридного пластиката'), ('Шв', 'Защитный шланг из поливинилхлоридного пластиката'), ('Шп', 'Зашитный шланг из полиэтилена'), ('П', 'Наружная оболочка из полимеров, не содержащих галогенов')], default='E', max_length=150),
        ),
        migrations.AddField(
            model_name='spec',
            name='screening',
            field=models.CharField(blank=True, choices=[('', 'Без экрана'), ('Э', 'С экраном')], max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='shape',
            field=models.CharField(choices=[('', 'Круглые'), ('П', 'Плоские')], default='E', max_length=50),
        ),
        migrations.AlterField(
            model_name='spec',
            name='insulation',
            field=models.CharField(choices=[('В', 'Поливинилхлорид'), ('Пв', 'Сшитый полиэтилен'), ('П', 'Полимерные композиции, не содержащие галогенов')], default='E', max_length=100),
        ),
        migrations.AlterField(
            model_name='spec',
            name='material',
            field=models.CharField(blank=True, choices=[('', 'Медь'), ('А', 'Алюминий')], max_length=2),
        ),
    ]
