# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koorsuch_app', '0003_auto_20170421_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='firefighting_spec',
            field=models.CharField(choices=[('', 'вы не должны это видеть'), ('-LS', 'С пониженным дымо- и газовыделением'), ('-HF', 'Не выделяющие коррозионно-активных газообразных продуктов при горении'), ('-FRLS', 'Огнестойкие, с пониженным дымо- и газовыделением'), ('-FRHF', 'Огнестойкие и не выделяющие коррозионно-активных газообразных продуктов при горении')], max_length=200, null=True),
        ),
    ]
