# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koorsuch_app', '0004_auto_20170506_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='extra_wires',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cable',
            name='wire',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='spec',
            name='firefighting_spec',
            field=models.CharField(blank=True, choices=[('', 'вы не должны это видеть'), ('-LS', 'С пониженным дымо- и газовыделением'), ('-HF', 'Не выделяющие коррозионно-активных газообразных продуктов при горении'), ('-FRLS', 'Огнестойкие, с пониженным дымо- и газовыделением'), ('-FRHF', 'Огнестойкие и не выделяющие коррозионно-активных газообразных продуктов при горении')], max_length=200, null=True),
        ),
    ]
