# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koorsuch_app', '0006_auto_20170506_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='extra_gauge',
            field=models.FloatField(blank=True, choices=[(1.5, 1.5), (2.5, 2.5), (4, 4), (6, 6), (10, 10), (16, 16), (25, 25), (35, 35), (50, 50), (70, 70), (95, 95), (120, 120), (150, 150), (185, 185), (240, 240), (300, 300), (400, 400), (500, 500), (625, 625), (630, 630), (800, 800), (1000, 1000)], null=True),
        ),
    ]
